### ISSUE TITLE
[Idea] Any reason it is not editable / updatable?

### ISSUE THREAD

**Issue by Tackgnol** [makedatanotlore/scvmatorium#32]
Hi, 

inspired by DND Beyond I was thinking about making something similar for Mork Bork. Have you considered it? You already have quite the thing here, would you be open to PR that for starters allows the user to Heal / Take damage or Add / Lose an Item? 
It's perfectly ok to come back to me saying: "No, bugger off" or "Let's see the PR first ". :) 

Edit: As I try for the heck of it, this would be hefty, at least how I understand the state. 
1. Find the hp one in the `state.smalls` 
2. Replace the values section of it with new `{hp: value}`
3. `Splice` the smalls at the hp index and push the new one, or place it on that index (makes little difference) 
4. Push the new state. 

Will take a further look for fun, must a simpler way :)

**Comment by makedatanotlore** [comment]
Heya, it's definitely not impossible but it's also not in the scope of this project as I see it. If you wanna have a go at it you're welcome to! I do believe there is a character manager called Modron that's specifically for MB. Maybe that can work for your use case!

**Comment by Tackgnol** [comment]
Thank you so much for your reply.
I am in the process of making my own, still some time off till any 'published' version. 

http://corpserun.tackgnol.usermd.net/
